version: "3"
services: 
  mysql_knex:
    container_name: mysql_knex
    hostname: mysql_knex
    image: mysql
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    ports:
      - 3309:3309
    environment:
      MYSQL_ROOT_PASSWORD: 00000000
      MYSQL_DATABASE: bank_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 00000000
      TZ: America/Sao_Paulo

  